// File: frontend/src/styles/theme.js

/**
 * Theme Definition (The Blueprint)
 *
 * This file defines the visual appearance of the application for different modes.
 * It specifies the actual configuration (palette colors, typography settings,
 * default component styles, etc.) for both light and dark themes.
 *
 * It exports a function (`createCustomTheme`) which takes a mode ('light' or 'dark')
 * and returns a complete, ready-to-use MUI theme object generated by
 * MUI's `createTheme` based on the configurations defined herein.
 */

import { createTheme } from '@mui/material/styles';
import { red } from '@mui/material/colors';

// VirtualMD brand color palette based on the logo
const brandColors = {
  lightBlue: '#27A9E0', // Light blue from logo
  blue: '#1579BC',      // Mid-blue from logo
  purple: '#7E3F98',    // Purple from logo
  lightPurple: '#9E5FB0' // Lighter purple variation
};

// Function that returns theme options based on mode
const getDesignTokens = (mode) => {
  // Ensure mode is strictly 'light' or 'dark'
  const effectiveMode = mode === 'dark' ? 'dark' : 'light';

  // Base configuration shared by both modes
  const baseConfig = {
      typography: {
          fontFamily: '"Roboto", "Helvetica", "Arial", sans-serif',
          h1: { fontSize: '3rem', fontWeight: 600 },
          h2: { fontSize: '2.5rem', fontWeight: 600 },
          h3: { fontSize: '2rem', fontWeight: 600 },
          h4: { fontSize: '1.75rem', fontWeight: 600 },
          h5: { fontSize: '1.5rem', fontWeight: 600 },
          h6: { fontSize: '1.25rem', fontWeight: 600 },
      },
      components: {
          MuiButton: {
              styleOverrides: {
                  root: {
                      borderRadius: '20px',
                      textTransform: 'none',
                  }
              }
          },
          MuiCard: {
              styleOverrides: {
                  root: {
                      borderRadius: '16px',
                  }
              }
          }
      }
  };

  // Mode-specific palette overrides
  const modeSpecificPalette = effectiveMode === 'dark'
      ? { // Dark Mode Palette
          primary: { main: brandColors.lightBlue },
          secondary: { main: brandColors.lightPurple },
          error: { main: red.A400 },
          background: { default: '#121212', paper: '#1e1e1e' },
          text: { primary: '#ffffff', secondary: 'rgba(255, 255, 255, 0.7)', disabled: 'rgba(255, 255, 255, 0.5)' },
      }
      : { // Light Mode Palette
          primary: { main: brandColors.blue },
          secondary: { main: brandColors.purple },
          error: { main: red.A400 },
          background: { default: '#f4f6f8', paper: '#ffffff' },
          text: { primary: '#172b4d', secondary: '#6b778c' },
      };

  // Merge base config with mode-specific palette
  return {
      ...baseConfig, // Spread base config first
      palette: {
          mode: effectiveMode, // Explicitly use the validated mode string
          ...modeSpecificPalette, // Spread mode-specific colors
          brandColors, // Add custom colors
          common: {
              black: '#000',
              white: '#fff',
          },
      },
  };
};

// Function that creates the actual theme object using MUI's createTheme
const createCustomTheme = (mode) => createTheme(getDesignTokens(mode));

// Export the function that CREATES the theme object
export default createCustomTheme;
