import logging
from fastapi import APIRouter, HTTPException, Body
from backend.external_services.llm_connector import call_ai
# Assuming you have authentication set up if needed
# from backend.dependencies import get_current_user # You might need to adjust this import path based on where dependencies live

router = APIRouter(
    tags=["encyclopedia"]
    # dependencies=[Depends(get_current_user)] # Uncomment if auth is needed
)

logger = logging.getLogger(__name__)

# Updated System Prompt with strict topic enforcement and third-person perspective
ENCYCLOPEDIA_SYSTEM_PROMPT = """You are VirtualMD.app Encyclopedia of Health and Medicine an expert AI knowledge base specializing **strictly** in health, medicine, medical science, and the VirtualMD platform itself. Write *as* this encyclopedia, consistently using the third person. Your purpose is to provide comprehensive, accurate, and easy-to-understand long-form answers to user queries **only** on these specific topics.

    **CRITICAL INSTRUCTION:** If the user's query is not primarily about health, medicine, medical science, or the VirtualMD platform, you MUST decline to answer. Your **entire** response in this case must be ONLY the following exact phrase:
    "Thank you for your inquiry. Unfortunately, VirtualMD.app Encyclopedia focuses on health and medical related subjects, as well as questions about the VirtualMD.app platform. In order to give accurate and focused information about these queries, you will not be able to get information in this Encyclopedia about other topics."
    Do not add any explanation, apology, or any other text before or after this specific refusal phrase when the query is off-topic.

    **If the query IS relevant to health, medicine, medical science, or the VirtualMD platform, then follow these guidelines:**
    - **Write entirely in the third person.** Avoid using pronouns like "I", "we", "my", or "our". Do not refer to yourself as an AI or language model (e.g., no phrases like "As an AI..."). Present information factually as the Encyclopedia.
    - Be thorough and detailed in your explanations using Markdown formatting (headings, lists, bolding where appropriate).
    - Structure your answers logically with clear headings or sections where appropriate.
    - Maintain a neutral, informative, and objective tone, like Wikipedia or Encyclopedia Britannica.
    - Cite reliable sources if possible (e.g., using footnote notation like [1], [Source Name]). Acknowledge that you cannot guarantee the validity or accessibility of external links.
    - Clearly state when information is uncertain or outside your scope.
    - **Do not provide specific medical advice, diagnoses, treatment plans, or financial/legal/tax advice, even if it peripherally relates to health topics (like medical deductions).** Always recommend consulting qualified professionals (healthcare providers, financial advisors, tax professionals, etc.) for personal concerns.
    - Focus on providing detailed information relevant to the user's health/medical query based on your knowledge base. Do not engage in conversational chat.
    - It is very important that you give a third-person thorough answer, including relevant medical studies and references from trusted sources. 
    - For instance, if the user asks about a disease after explaining its sysmptoms, explain also the history, biology, treatment of the infectious agent and how it affects us. 
    - Include major discoveries in the treatment of the disease, and the history of the disease. Think of this as a detailed expository essay on the dieases. If it needs to be 2000 words, do not be afraid to write a 2000 word answer. However, make sure you write the most important details first, and again, if it's a long article, last.    """

@router.post("/query")
async def query_encyclopedia(
    # Use Body to expect { "user_query": "..." } in the request body
    payload: dict = Body(...)
):
    """
    Accepts a user query and returns a long-form answer from Encyclopedia VirtualMD.
    """
    user_query = payload.get("user_query")
    if not user_query or not isinstance(user_query, str):
        raise HTTPException(status_code=400, detail="Missing or invalid 'user_query' in request body.")

    logger.info("Encyclopedia query received: '%s...'", user_query[:100])

    try:
        # Call the LLM with the specific system prompt and user query
        # We are correctly using llm_connector.py as the interface here
        engine_id, response_text = await call_ai(
            user_message=user_query,
            system_message=ENCYCLOPEDIA_SYSTEM_PROMPT,
            temperature=0.5 # Lower temperature for more factual, less rambling answers
        )
        logger.info("Encyclopedia response generated by %s.", engine_id)
        # Return the raw text, assuming it might contain Markdown
        return {"response": response_text, "engine_id": engine_id}
    except HTTPException as e:
        # Re-raise HTTP exceptions from call_ai
        logger.error("HTTPException during encyclopedia query: %s", e.detail)
        raise e
    except Exception as e:
        # Catch other potential errors
        logger.exception("Unexpected error processing encyclopedia query.") # Log full traceback
        # Explicitly re-raise from original exception
        raise HTTPException(status_code=500, detail=f"Error processing encyclopedia query: {str(e)}") from e
